---
functional:
  - Сайт должен иметь возможность авторизации и регистрации
  - Сайт должен иметь возможность авторизации и регистрации через Github и Discord
  - На сайте можно редактировать свой профиль
  - На сайте можно просматривать свою статистику по играм
  - На сайте должна быть возможность создавать игру
  - На сайте должна быть возможность удалять созданную игру
  - В игре должна быть возможность устанавливать уровень сложности, язык программирования, время игры, задания
  - Каждый игрок может видеть код своего соперника в режиме он-лайн
  - Каждый игрок должен иметь возможность проверки своего решения
  - К игре можно переподключиться в случае вылета, если она не закончена
  - После завершения игры должно выводиться модальное окно с итогами игры
  - На сайте должна быть возможность создавать игры без регистрации
  - На сайте должна быть возможность просматривать рейтинги других игроков
  - На сайте должна быть возможность просматривать историю игр других игроков
  - На сайте должна быть возможность пригласить пользователя в игру
  - На сайте можно общаться в чате
  - На сайте можно создать игру с ботом
  - На сайте можно отправить личное сообщение
  - На сайте должна быть возможность создавать турниры
  - На сайте можно изменять звук уведомления об итогах игры
non-functional:
 - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен быть удобным на мобильном устройстве
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров
 - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - В игре может принимать участие более двух игроков
  - На сайте есть возможность смены языка на русский
  - На сайте должна быть возможность перехода в документацию
  - На сайте должна быть возможность отправки фидбека на всех страницах
  - На сайте должны быть подсказки к функционалу и/или обучение при регистрации
